### ISSUE TITLE
这样在index中post地址更改主选课的地址是正确的吗？

### ISSUE THREAD

**Issue by OPlincn** [GrinZero/sztu-scramble-for-class#1]
在将post的地址改为主选课地址
`https://jwxt.sztu.edu.cn/jsxsd/xsxkkc/xsxkBxqjhxk?kcxx=&skls=&skxq=&skjc=&sfym=false&sfct=true&sfxx=true&skfs=`
后
显示
`getCourseList timeout
chooseCourse timeout 1`
是合理的吗？我将目前可选的课程id加入到config里，跑起来也没有选上
晚点补图T_T

**Comment by GrinZero** [comment]
注意一下参数变化～我指payload

**Comment by GrinZero** [comment]
> 注意一下参数变化～我指payload

payload->图中的body

**Comment by OPlincn** [comment]
学长你好，军训刚搞回来。我将post的地址更改了(原来的也试了一次)
<img width="1121" alt="Screen Shot 2023-02-23 at 9 34 45 PM" src="https://user-images.githubusercontent.com/49088507/220923004-9086f59f-4126-41b3-8df2-77c4935f7ce2.png">
但是跑出来仍是
<img width="227" alt="Screen Shot 2023-02-23 at 9 40 02 PM" src="https://user-images.githubusercontent.com/49088507/220923297-d0a707b3-e518-46d3-becb-183596c3d305.png">

不理解T_T 没学过javascript, config.json里的内容已经改好了

**Comment by GrinZero** [comment]
~我更新了版本，是教务更新导致原本的部分失效，目前已恢复。
#timeout是我的语义问失误，实际上这里是delay，重试的delay

**Comment by OPlincn** [comment]
在确保post地址和body正确(我用的就是控制台得到的那个)
<img width="548" alt="Screen Shot 2023-02-24 at 12 52 52 PM" src="https://user-images.githubusercontent.com/49088507/221095283-03a41ffa-9301-44e6-ba0f-8011e864b59f.png">


还有课程非主选人数不为0的情况下，运行，会提示
<img width="530" alt="Screen Shot 2023-02-24 at 12 50 53 PM" src="https://user-images.githubusercontent.com/49088507/221095302-6dbf1efa-baaa-4fa4-85c5-19dd84fdd301.png">
还有救吗T_T

**Comment by GrinZero** [comment]
害，我来吧，等我一下

**Comment by GrinZero** [comment]
![image](https://user-images.githubusercontent.com/70185413/221113407-5269adf8-020c-4a16-ad85-25e1709fe2e5.png)

**Comment by OPlincn** [comment]
排列组合了一下多个name，我觉得已经可以卑微的放弃了>_<
<img width="351" alt="Screen Shot 2023-02-24 at 9 10 39 PM" src="https://user-images.githubusercontent.com/49088507/221187251-041619d0-d3ed-4700-9fb3-a2810a946718.png">

<img width="380" alt="Screen Shot 2023-02-24 at 9 14 10 PM" src="https://user-images.githubusercontent.com/49088507/221187529-1112d346-16d9-4deb-b910-5dd2cc52be35.png">
这个name也是匹配元素之一吗，试了好几个;_;

**Comment by GrinZero** [comment]
目前的结构是
```ts
interface JX0404Item{
    id: string
    name: string
    type: '本学期计划选课'|'公选课选课'
}
```
你期望的config应该是：
![image](https://user-images.githubusercontent.com/70185413/221187577-ac374cb4-1b79-4a87-827d-5f54a1d76b12.png)

```js
[
  {
     id: '202220232002356',
     name: '体育俱乐部 II',
     type: '本学期计划选课' 
  }
]
```

**Comment by OPlincn** [comment]
好的 麻烦学长了。
我印象里我有用过这个name，不过是**直接cv**的课程名字。明天打开我再试>_<
